import pandas as pd
import requests

_player_stat_cache = {}

def getFixturesFromAPI():
    """
    Gets all the fixtures for the season from the API and returns them as a dataframe
    """
    url = 'https://fantasy.premierleague.com/api/'
    F = requests.get(url+'fixtures/').json()

    fixtures = F
    fixtures = sorted(fixtures, key=lambda x: x['id'])

    df = pd.DataFrame(fixtures)

    features = [
        'id', 'event', 'finished', 'team_h', 'team_a', 'team_h_score', 'team_a_score',
        'team_a_difficulty', 'team_h_difficulty', 'stats', 'kickoff_time', 
    ]

    df = df[features]

    df['kickoff_time'] = pd.to_datetime(df['kickoff_time'])

    return df


def getPlayerStatFromAPI(player_id):
    """
    Gets the data from a specific player for each gameweek and returns it as a dataframe
    """
    if player_id in _player_stat_cache:
        return _player_stat_cache[player_id]

    url = 'https://fantasy.premierleague.com/api/'
    P = requests.get(url+f'element-summary/{player_id}/').json()

    history = P['history']
    history = sorted(history, key=lambda x: x['round'])

    df = pd.DataFrame(history)

    features = [
        'element', 'fixture', 'kickoff_time', 'opponent_team', 'total_points', 'was_home', 'team_h_score', 'team_a_score', 'round', 'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries', 'tackles', 'defensive_contribution', 'starts', 'expected_goals', 'expected_assists', 'expected_goal_involvements', 'expected_goals_conceded', 'value', 'selected', 'transfers_in', 'transfers_out'
        ]

    df = df[features]

    #convert strings to numbers?
    numeric_cols = ['expected_goals', 'expected_assists', 'expected_goal_involvements',
                    'expected_goals_conceded', 'influence', 'creativity', 'threat', 'ict_index']
    df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

    _player_stat_cache[player_id] = df

    return df


def getPlayersFromAPI():
    """
    Gets all the players for the season and their total/general season stats from the API and returns them as a dataframe
    """
    url = 'https://fantasy.premierleague.com/api/'
    P = requests.get(url+'bootstrap-static/').json()

    players = P['elements']
    players = sorted(players, key=lambda x: x['id'])

    df = pd.DataFrame(players)

    features = [
        'minutes', 'starts', 'starts_per_90',
        'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals',
        'expected_goals', 'expected_assists', 'expected_goal_involvements', 'expected_goals_conceded',
        'expected_goals_per_90', 'expected_assists_per_90', 'expected_goal_involvements_per_90', 'expected_goals_conceded_per_90',
        'saves', 'saves_per_90', 'penalties_saved', 'penalties_missed',
        'bonus', 'bps', 'total_points', 'points_per_game',

        'form', 'ep_next', 'ep_this',
        'selected_by_percent',
        'transfers_in_event', 'transfers_out_event',
        'now_cost',
        'status', 'chance_of_playing_next_round', 'chance_of_playing_this_round',

        'id', 'element_type', 'team', 'first_name', 'second_name',

        'ict_index',
    ]  

    # for _, player in df.iterrows():
    #     print(player['first_name'], player['second_name'], player['team'])

    df = df[features]
    return df

def getPlayerFromID(player_id):
    """
    Gets a player's season and gamebygame stats from their player ID
    """
    df_season = getPlayersFromAPI()
    player = df_season[df_season['id'] == player_id]
    if len(player) == 0:
        return None
    else:
        player = player.iloc[0]

    df_gameweek = getPlayerStatFromAPI(player['id'])
    return player, df_gameweek #returns a tuple of a series, and a dataframe

#again code below is generated by claude
def buildOpponentXGCLookup(through_gw):
    """
    Build the (team_id, gameweek) -> xGC-per-game lookup from the live FPL API,
    using only matches BEFORE `through_gw`. Mirrors computeOpponentxGCLookup.
    """
    players = getPlayersFromAPI()

    all_player_data = []
    for _, p in players.iterrows():
        try:
            stat = getPlayerStatFromAPI(p['id'])
            #only matches strictly before the target gameweek (no leakage)
            stat = stat[stat['round'] <= through_gw]
            all_player_data.append(stat)
        except Exception as e:
            # print(f"  skip player {p['id']}: {e}")
            continue

    season_data = pd.concat(all_player_data, ignore_index=True)
    return computeOpponentxGCLookup(season_data)

def determineBlankDoubleGWs(player_id, current_gw, endGw, fixturesdf):
    player_season_stats, _ = getPlayerFromID(player_id)
    upcoming_games = []
    for i in range(current_gw, endGw+1): #include the +1 so that we include the end_gw fixture
        next_fuxture = fixturesdf[(fixturesdf['event'] == i) & ((fixturesdf['team_h'] == player_season_stats['team']) | (fixturesdf['team_a'] == player_season_stats['team']))] #get the next fixture for the player
        if len(next_fuxture) == 0: #blank gw
            upcoming_games.append(0)
        elif len(next_fuxture) == 1: #single gw
            upcoming_games.append(1)
        else: #double gw
            upcoming_games.append(len(next_fuxture))
    return upcoming_games

def getPlayerIDFromName(first_name, second_name, full_player_id_list):
    for _, row in full_player_id_list.iterrows():
        if row['first_name'] == first_name and row['second_name'] == second_name:
            return row['id']
        
if __name__ == "__main__":
    full_player_id_list = getPlayersFromAPI()
    players = [
        ['Jordan', 'Pickford'],
        ['Matz', 'Sels'],
        ['Joško', 'Gvardiol'],
        ['Nikola', 'Milenković'],
        ['Daniel', 'Muñoz Mejía'],
        ['Milos', 'Kerkez'],
        ['Marc', 'Cucurella Saseta'],
        ['Mohamed', 'Salah'],
        ['Bryan', 'Mbeumo'],
        ['Jarrod', 'Bowen'],
        ['Antoine', 'Semenyo'],
        ['Jacob', 'Murphy'],
        ['Chris', 'Wood'],
        ['Yoane', 'Wissa'],
        ['Matheus', 'Santos Carneiro da Cunha'],
    ]

    for player in players:
        print(player[0], player[1], getPlayerIDFromName(player[0], player[1], full_player_id_list))

    