import numpy as np
import requests
import xgboost as xgb
import pandas as pd

from predictExpectedGoalsConceded.getCleanSheetDataset import flatten_lags, getLast5Matches, getNextMatch
from predictGoals.getGoalsDataset import computeOpponentxGCLookup

P_D = { #points distribution
    "minutes": [2, 2, 2, 2],
    "goals_scored": [10, 6, 5, 4], 
    "assists": [3, 3, 3, 3],
    "clean_sheets": [4, 4, 1, 0],
}

#---------------------Utility for current data---------------------
def getFixturesFromAPI():
    """
    Gets all the fixtures for the season from the API and returns them as a dataframe
    """
    url = 'https://fantasy.premierleague.com/api/'
    F = requests.get(url+'fixtures/').json()

    fixtures = F
    fixtures = sorted(fixtures, key=lambda x: x['id'])

    df = pd.DataFrame(fixtures)

    features = [
        'id', 'event', 'finished', 'team_h', 'team_a', 'team_h_score', 'team_a_score',
        'team_a_difficulty', 'team_h_difficulty', 'stats', 'kickoff_time', 
    ]

    df = df[features]

    df['kickoff_time'] = pd.to_datetime(df['kickoff_time'])

    return df


def getPlayerStatFromAPI(player_id):
    """
    Gets the data from a specific player for each gameweek and returns it as a dataframe
    """
    url = 'https://fantasy.premierleague.com/api/'
    P = requests.get(url+f'element-summary/{player_id}/').json()

    history = P['history']
    history = sorted(history, key=lambda x: x['round'])

    df = pd.DataFrame(history)

    features = [
        'element', 'fixture', 'kickoff_time', 'opponent_team', 'total_points', 'was_home', 'team_h_score', 'team_a_score', 'round', 'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries', 'tackles', 'defensive_contribution', 'starts', 'expected_goals', 'expected_assists', 'expected_goal_involvements', 'expected_goals_conceded', 'value', 'selected', 'transfers_in', 'transfers_out'
        ]

    df = df[features]

    #convert strings to numbers?
    numeric_cols = ['expected_goals', 'expected_assists', 'expected_goal_involvements',
                    'expected_goals_conceded', 'influence', 'creativity', 'threat', 'ict_index']
    df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

    return df


def getPlayersFromAPI():
    """
    Gets all the players for the season and their total/general season stats from the API and returns them as a dataframe
    """
    url = 'https://fantasy.premierleague.com/api/'
    P = requests.get(url+'bootstrap-static/').json()

    players = P['elements']
    players = sorted(players, key=lambda x: x['id'])

    df = pd.DataFrame(players)

    features = [
        'minutes', 'starts', 'starts_per_90',
        'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'own_goals',
        'expected_goals', 'expected_assists', 'expected_goal_involvements', 'expected_goals_conceded',
        'expected_goals_per_90', 'expected_assists_per_90', 'expected_goal_involvements_per_90', 'expected_goals_conceded_per_90',
        'saves', 'saves_per_90', 'penalties_saved', 'penalties_missed',
        'bonus', 'bps', 'total_points', 'points_per_game',

        'form', 'ep_next', 'ep_this',
        'selected_by_percent',
        'transfers_in_event', 'transfers_out_event',
        'now_cost',
        'status', 'chance_of_playing_next_round', 'chance_of_playing_this_round',

        'id', 'element_type', 'team', 'first_name', 'second_name',

        'ict_index',
    ]  

    # for _, player in df.iterrows():
    #     print(player['first_name'], player['second_name'], player['team'])

    df = df[features]
    return df

#again code below is generated by claude
def buildOpponentXGCLookup(through_gw):
    """
    Build the (team_id, gameweek) -> xGC-per-game lookup from the live FPL API,
    using only matches BEFORE `through_gw`. Mirrors computeOpponentxGCLookup.
    """
    players = getPlayersFromAPI()

    all_player_data = []
    for _, p in players.iterrows():
        try:
            stat = getPlayerStatFromAPI(p['id'])
            #only matches strictly before the target gameweek (no leakage)
            stat = stat[stat['round'] <= through_gw]
            all_player_data.append(stat)
        except Exception as e:
            # print(f"  skip player {p['id']}: {e}")
            continue

    season_data = pd.concat(all_player_data, ignore_index=True)
    return computeOpponentxGCLookup(season_data)


#----------------------Prediction functions---------------------
def predictMinutes(player_stats, gw, season):
    model = xgb.XGBClassifier()
    model.load_model('predictMinutes/minutes_model.json')

    features = getMinutesFeatures(player_stats, gw, season)
    features = features[model.feature_names_in_] #enforces column order

    # for _, feature in features.iterrows():
    #     print(feature)
    prob = model.predict_proba(features)[0, 1] #predict the probability of playing
    cls = int(model.predict(features)[0]) #hard 1/0 decision

    return prob, cls

def getMinutesFeatures(df, gw, season):
    position_dict = {"GK": 1, "DEF": 2, "MID": 3, "FWD": 4}

    started_last_match = -1 #whether the player started in the last match (1 gw behind)
    starts_last_5 = -1 #how many times the player started in the last 5 games
    player_position = -1
    days_since_last_match = -1 #how many days since the player's last match
    days_since_last_team_match = -1 #how many days since the player's team last played a match
    days_till_next_match = -1 #how many days until the player's next match (after the current gw)

    minutes_last_match = -1 #1 gw behind
    minutes_last_match_plus_1 = -1 #2 gw behind
    minutes_last_match_plus_2 = -1 #3 gw behind
    minutes_last_match_plus_3 = -1 #4 gw behind
    minutes_last_match_plus_4 = -1 #5 gw behind

    games_played_last_5 = -1 #how many games the player has played in the last 5 games


    row = df[df['round'] == gw].iloc[0] #current gw row
    idx = df.index[df['round'] == gw][0] #past id

    player_position = position_dict[row['position']]

    started_last_match = 1 if idx > 0 and df.iloc[idx-1]['starts'] == 1 else 0

    minutes_last_match = df.iloc[idx-1]['minutes'] if idx > 0 else np.nan
    minutes_last_match_plus_1 = df.iloc[idx-2]['minutes'] if idx > 1 else np.nan
    minutes_last_match_plus_2 = df.iloc[idx-3]['minutes'] if idx > 2 else np.nan
    minutes_last_match_plus_3 = df.iloc[idx-4]['minutes'] if idx > 3 else np.nan
    minutes_last_match_plus_4 = df.iloc[idx-5]['minutes'] if idx > 4 else np.nan

    #days since the team last played a match
    days_since_last_team_match = (pd.to_datetime(row['kickoff_time']) - pd.to_datetime(df.iloc[idx-1]['kickoff_time'])).days if idx > 0 else np.nan #current gw kickoff time - last gw kickoff time

    #days since the player last played a match
    gw_last_played = np.nan #holds the gw of the player's last match
    for i in range(idx -1, -1, -1): #look back until the player played in a match
        if df.iloc[i]['minutes'] > 0:
            gw_last_played = df.iloc[i]['round']
            break
    days_since_last_match = (pd.to_datetime(row['kickoff_time']) - pd.to_datetime(df[df['round'] == gw_last_played].iloc[0]['kickoff_time'])).days if not pd.isna(gw_last_played) else np.nan #current gw kickoff time - last played gw kickoff time

    games_played_last_5 = sum(1 for i in range(idx-1, idx-6, -1) if i >= 0 and df.iloc[i]['minutes'] > 0)
    starts_last_5 = sum(1 for i in range(idx-1, idx-6, -1) if i >= 0 and df.iloc[i]['starts'] == 1)

    days_till_next_match = (pd.to_datetime(df.iloc[idx+1]['kickoff_time']) - pd.to_datetime(row['kickoff_time'])).days if idx < len(df) - 1 else np.nan #next gw kickoff time - current gw kickoff time
        
    features = {
        'season': season,
        'gameweek': gw,
        
        'player_position': player_position,
        'started_last_match': started_last_match,

        'minutes_last_match': minutes_last_match,
        'minutes_last_match_plus_1': minutes_last_match_plus_1,
        'minutes_last_match_plus_2': minutes_last_match_plus_2,
        'minutes_last_match_plus_3': minutes_last_match_plus_3,
        'minutes_last_match_plus_4': minutes_last_match_plus_4,

        'games_played_last_5': games_played_last_5,
        'starts_last_5': starts_last_5,

        'days_since_last_match': days_since_last_match,
        'days_since_last_team_match': days_since_last_team_match,
        'days_till_next_match': days_till_next_match,
    }

    return pd.DataFrame([features])



def predictGoals(player_stats, gw, season, opponent_xGC):
    model = xgb.XGBRegressor()
    model.load_model('predictGoals/goals_model.json')

    features = getGoalsFeatures(player_stats, gw, season, opponent_xGC)
    features = features[model.feature_names_in_] #enforces column order

    # print(model.feature_names_in_)

    # for _, feature in features.iterrows():
    #     print(feature)
    expected_goals = float(model.predict(features)[0]) #predict the expected goals for the current gw

    return expected_goals


def getGoalsFeatures(df, gw, season, opponent_xGC):
    position_dict = {"GK": 1, "DEF": 2, "MID": 3, "FWD": 4}
    player_position = -1

    lag_features = ['expected_goals', 'expected_assists', 'influence', 'threat', 'creativity', 'goals_scored', 'bps', 'minutes']
    lag_data = {f'{feat}_lag_{i}': [] for feat in lag_features for i in range(1, 6)} #lag features for the last 5 matches (1 gw behind, 2 gws behind, etc.)

    goals_per_90_season_to_date = -1 #the player's number of goals per 90 minutes in the season to date (up to the current gw)
    xGoals_per_90_season_to_date = -1 #the player's number of xGoals per 90 minutes in the season to date (up to the current gw)

    is_home = -1 #whether the player's team is playing at home in the current gw

    row = df[df['round'] == gw].iloc[0] #current gw row
    idx = df.index[df['round'] == gw][0] #index of the current gw row

    player_position = position_dict[row['position']]
        
    for feat in lag_features:
        for lag in range(1, 6):
            lag_data[f'{feat}_lag_{lag}'] = df.iloc[idx - lag][feat] if idx >= lag else np.nan
            

    #calculate goals per 90 season to date
    minutes_played_season_to_date = df.iloc[:idx]['minutes'].sum()

    goals_scored_season_to_date = df.iloc[:idx]['goals_scored'].sum()
    xGoals_season_to_date = df.iloc[:idx]['expected_goals'].sum()

    goals_per_90_season_to_date = (goals_scored_season_to_date / minutes_played_season_to_date * 90) if minutes_played_season_to_date > 0 else np.nan
    xGoals_per_90_season_to_date = (xGoals_season_to_date / minutes_played_season_to_date * 90) if minutes_played_season_to_date > 0 else np.nan

    is_home = 1 if row['was_home'] == True else 0
            
    features = {
        'season': season,
        'gameweek': gw,
        
        'player_position': player_position,
        
        **lag_data,

        'goals_per_90_season_to_date': goals_per_90_season_to_date,
        'xGoals_per_90_season_to_date': xGoals_per_90_season_to_date,
        
        'is_home': is_home,

        'opponent_xGC_per_game': opponent_xGC
    }

    return pd.DataFrame([features])

def predictAssists(player_stats, gw, season, opponent_xGC):
    model = xgb.XGBRegressor()
    model.load_model('predictAssists/assists_model.json')

    features = getAssistsFeatures(player_stats, gw, season, opponent_xGC)
    features = features[model.feature_names_in_] #enforces column order

    # print(model.feature_names_in_)

    # for _, feature in features.iterrows():
    #     print(feature)
    expected_assists = float(model.predict(features)[0]) #predict the expected assists for the current gw

    return expected_assists


def getAssistsFeatures(df, gw, season, opponent_xGC):
    position_dict = {"GK": 1, "DEF": 2, "MID": 3, "FWD": 4}
    player_position = -1

    lag_features = ['expected_goals', 'expected_assists', 'influence', 'threat', 'creativity', 'assists', 'bps', 'minutes']
    lag_data = {f'{feat}_lag_{i}': [] for feat in lag_features for i in range(1, 6)} #lag features for the last 5 matches (1 gw behind, 2 gws behind, etc.)

    assists_per_90_season_to_date = -1 #the player's number of assists per 90 minutes in the season to date (up to the current gw)
    xAssists_per_90_season_to_date = -1 #the player's number of xAssists per 90 minutes in the season to date (up to the current gw)

    is_home = -1 #whether the player's team is playing at home in the current gw

    row = df[df['round'] == gw].iloc[0] #current gw row
    idx = df.index[df['round'] == gw][0] #index of the current gw row

    player_position = position_dict[row['position']]
        
    for feat in lag_features:
        for lag in range(1, 6):
            lag_data[f'{feat}_lag_{lag}'] = df.iloc[idx - lag][feat] if idx >= lag else np.nan
            

    #calculate assists per 90 season to date
    minutes_played_season_to_date = df.iloc[:idx]['minutes'].sum()

    assists_scored_season_to_date = df.iloc[:idx]['assists'].sum()
    xAssists_season_to_date = df.iloc[:idx]['expected_assists'].sum()

    assists_per_90_season_to_date = (assists_scored_season_to_date / minutes_played_season_to_date * 90) if minutes_played_season_to_date > 0 else np.nan
    xAssists_per_90_season_to_date = (xAssists_season_to_date / minutes_played_season_to_date * 90) if minutes_played_season_to_date > 0 else np.nan

    is_home = 1 if row['was_home'] == True else 0
            
    features = {
        'season': season,
        'gameweek': gw,
        
        'player_position': player_position,
        
        **lag_data,

        'assists_per_90_season_to_date': assists_per_90_season_to_date,
        'xAssists_per_90_season_to_date': xAssists_per_90_season_to_date,
        
        'is_home': is_home,

        'opponent_xGC_per_game': opponent_xGC
    }

    return pd.DataFrame([features])

def predictExpectedGoalsConceded(team_id, fixtures_df, gw, season):
    model = xgb.XGBRegressor()
    model.load_model('predictExpectedGoalsConceded/cleansheet_model.json')

    team_fixtures = fixtures_df[
        (fixtures_df['event'] == gw) &
        ((fixtures_df['team_h'] == team_id) | (fixtures_df['team_a'] == team_id))
    ]
    if team_fixtures.empty:
        return np.nan  #blank gameweek for this team
    fixture = team_fixtures.iloc[0]
    

    features = getExpectedGoalsConcededFeatures(team_id, fixture, fixtures_df, gw, season)
    features = features[model.feature_names_in_] #enforces column order

    # print(model.feature_names_in_)

    # for _, feature in features.iterrows():
    #     print(feature)
    expected_goals_conceded = float(model.predict(features)[0]) #predict the expected goals conceded for the current gw

    return expected_goals_conceded

def getExpectedGoalsConcededFeatures(team_id, fixture, fixtures_df, gw, season):
    """
    Args:
        team_id (int): The ID of the team for which to predict expected goals conceded.
        fixture (pandas.Series): A Series containing the fixture for which to predict expected goals conceded. Must contain 'team_h', 'team_a', and 'kickoff_time' columns.
        fixtures_df (pandas.DataFrame): A DataFrame containing all fixtures for the season. Must contain 'team_h', 'team_a', 'kickoff_time', 'team_h_score', and 'team_a_score' columns.
        gw (int): The gameweek for which to predict expected goals conceded.
        season (int): The season for which to predict expected goals conceded.
    Returns:
        pandas.DataFrame: A DataFrame containing the features for the expected goals conceded prediction model.
    """
    player_team = team_id
    is_home = -1
    if fixture['team_h'] == team_id:
        opponent_team = fixture['team_a']
        is_home = 1
    else:        
        opponent_team = fixture['team_h']
        is_home = 0

    player_lagged_GC = []
    player_lagged_GS = []
    player_days_rest = 0
    player_days_till_next = 0

    opp_lagged_GC = []
    opp_lagged_GS = []
    opp_days_rest = 0
    opp_days_till_next = 0

    player_past_fixtures = getLast5Matches(player_team, fixture['kickoff_time'], fixtures_df)
    if len(player_past_fixtures) > 0:
        last_match = player_past_fixtures.tail(1).iloc[0]
        player_days_rest = (fixture['kickoff_time'] - last_match['kickoff_time']).days
    else:
        player_days_rest = np.nan

    next_match = getNextMatch(player_team, fixture['kickoff_time'], fixtures_df)
    if not next_match.empty:
        player_days_till_next = (next_match.iloc[0]['kickoff_time'] - fixture['kickoff_time']).days
    else:
        player_days_till_next = np.nan


    for _, past_fix in player_past_fixtures.iterrows():
        if past_fix['team_h'] == player_team:
            player_lagged_GC.append(past_fix['team_a_score']) #the opponent's goals scored = team's goals conceded
            player_lagged_GS.append(past_fix['team_h_score'])


        else:
            player_lagged_GC.append(past_fix['team_h_score'])
            player_lagged_GS.append(past_fix['team_a_score'])


    #calculate metrics for the opponent team
    opp_past_fixtures = getLast5Matches(opponent_team, fixture['kickoff_time'], fixtures_df)
    if len(opp_past_fixtures) > 0:
        last_match = opp_past_fixtures.tail(1).iloc[0]
        opp_days_rest = (fixture['kickoff_time'] - last_match['kickoff_time']).days
    else:
        opp_days_rest = np.nan

    next_match = getNextMatch(opponent_team, fixture['kickoff_time'], fixtures_df)
    if not next_match.empty:
        opp_days_till_next = (next_match.iloc[0]['kickoff_time'] - fixture['kickoff_time']).days
    else:
        opp_days_till_next = np.nan

    for _, past_fix in opp_past_fixtures.iterrows():
        if past_fix['team_h'] == opponent_team:
            opp_lagged_GC.append(past_fix['team_a_score']) #the opponent's goals scored = team's goals conceded
            opp_lagged_GS.append(past_fix['team_h_score'])
        else:
            opp_lagged_GC.append(past_fix['team_h_score'])
            opp_lagged_GS.append(past_fix['team_a_score'])


    #reverse the lagged lists so that the most recent match is first
    player_GC_reversed = player_lagged_GC[::-1]
    player_GS_reversed = player_lagged_GS[::-1]
    opp_GC_reversed = opp_lagged_GC[::-1]
    opp_GS_reversed = opp_lagged_GS[::-1]

    features = {
        'season': season,
        'gameweek': fixture['event'],
        'team': player_team,
        'opponent_team': opponent_team,
        'is_home': is_home,
        **flatten_lags(player_GC_reversed, 'lagged_GC'),
        **flatten_lags(player_GS_reversed, 'lagged_GS'),
        'days_rest': player_days_rest,
        'days_till_next': player_days_till_next,
        **flatten_lags(opp_GC_reversed, 'opponent_lagged_GC'),
        **flatten_lags(opp_GS_reversed, 'opponent_lagged_GS'),
        'opponent_days_rest': opp_days_rest,
        'opponent_days_till_next': opp_days_till_next,
        'goals_conceded': fixture['team_a_score'],
    }

    return pd.DataFrame([features])

def convertExpectedGoalsConcededToCleanSheetProb(expected_goals_conceded):
    """
    Converts the expected goals conceded to a clean sheet probability using a Poisson distribution.
    """
    # P(X=0) = e^(-lambda) where lambda is the expected goals conceded
    clean_sheet_prob = np.exp(-expected_goals_conceded)
    return clean_sheet_prob


def calculatePlayerExpectedStats(player_id, gameweek, season, full_player_id_list, fixtures_df, xgc_lookup):
    # print(full_player_id_list[full_player_id_list['id'] == player_id][['first_name', 'second_name', 'team']])
    player_stat = getPlayerStatFromAPI(player_id) #gets the player's stats for each gameweek

    #convert player position from id to string
    pos_map = {1: 'GK', 2: 'DEF', 3: 'MID', 4: 'FWD'}
    element_type = full_player_id_list[full_player_id_list['id'] == player_id].iloc[0]['element_type']
    player_stat['position'] = pos_map[element_type]
    
    player_team_id = full_player_id_list[full_player_id_list['id'] == player_id].iloc[0]['team'] #gets the player's team id

    gw_rows = player_stat[player_stat['round'] == gameweek]
    if gw_rows.empty: #for when there is no gw
        return None
    opponent_team_id = gw_rows.iloc[0]['opponent_team']
    opp_xgc = xgc_lookup.get((opponent_team_id, gameweek), np.nan)

    minutes_prob, minutes_cls = predictMinutes(player_stat, gameweek, season)

    expected_goals = predictGoals(player_stat, gameweek, season, opp_xgc)

    expected_assists = predictAssists(player_stat, gameweek, season, opp_xgc)

    expected_goals_conceded = predictExpectedGoalsConceded(player_team_id, fixtures_df, gameweek, season)
    clean_sheet_prob = convertExpectedGoalsConcededToCleanSheetProb(expected_goals_conceded)

    # diagnoseCleanSheetSpread(fixtures_df, gameweek, season)
    # df, per_team = diagnoseAcrossGameweeks(fixtures_df, season, range(1, 39))

    return {
        'minutes_prob': minutes_prob,
        'minutes_class': minutes_cls,
        'expected_goals': expected_goals,
        'expected_assists': expected_assists,
        'expected_goals_conceded': expected_goals_conceded,
        'clean_sheet_prob': clean_sheet_prob,
    }

def getExpectedPoints(stats, player_position):
    indexer = player_position - 1 #to get the lookup for the points value
    return P_D['minutes'][indexer]*stats['minutes_prob'] + P_D['goals_scored'][indexer]*stats['expected_goals'] + P_D['assists'][indexer]*stats['expected_assists'] + P_D['clean_sheets'][indexer]*stats['clean_sheet_prob']

def getTopPlayersForGameweek(gameweek, season):
    full_player_id_list = getPlayersFromAPI() #gets all the players and their overall stats
    fixtures_df = getFixturesFromAPI() #gets all the fixtures for the season

    print("building xgc lookup")
    xgc_lookup = buildOpponentXGCLookup(gameweek) #once per gw

    player_xp = []

    print("calculating xp stats")
    for _, player in full_player_id_list.iterrows():
        stats = calculatePlayerExpectedStats(player['id'], gameweek, season, full_player_id_list, fixtures_df, xgc_lookup)
        if stats is not None:
            xp = round(getExpectedPoints(stats, player['element_type']), 7)
            player_xp.append([player['first_name'], player['second_name'], player['team'], xp, stats])
            # print(player['first_name'], player['second_name'], ":", xp, "points")

    player_xp = sorted(player_xp, key=lambda p: p[3], reverse=True)

    print(f"-------Top Players for GW {gameweek}-------")
    for i in range(0, 20):
        print(f"{i+1}. ", player_xp[i][0], player_xp[i][1], player_xp[i][3])

    return player_xp


def main():
    season = 2526
    gameweek = 20

    getTopPlayersForGameweek(gameweek, season)


if __name__ == "__main__":
    main()


    



import matplotlib.pyplot as plt

def diagnoseCleanSheetSpread(fixtures_df, gameweek, season):
    for gw in range(1, 39):
        preds = {}
        for team_id in range(1, 21):
            try:
                preds[team_id] = predictExpectedGoalsConceded(team_id, fixtures_df, gw, season)
            except Exception as e:
                print(f"skip team {team_id}: {e}")
        s = pd.Series(preds, name='xGC').dropna()

        print(s.sort_values())
        print(s.describe())            # min, max, mean, std
        print(f"range: {s.max() - s.min():.3f}, std: {s.std():.3f}")

        s.hist(bins=15)
        plt.xlabel('predicted expected goals conceded')
        plt.ylabel('count')
        plt.title(f'Clean sheet model output spread — GW{gw}')
        plt.show()

def diagnoseAcrossGameweeks(fixtures_df, season, gw_range):
    rows = []
    for gw in gw_range:
        for team_id in range(1, 21):
            try:
                rows.append({'gw': gw, 'team': team_id,
                             'xGC': predictExpectedGoalsConceded(team_id, fixtures_df, gw, season)})
            except Exception:
                continue
    df = pd.DataFrame(rows).dropna()

    # 1. global spread of every prediction
    print("ALL PREDICTIONS:")
    print(df['xGC'].describe())
    print(f"global std: {df['xGC'].std():.3f}  (real-world ~0.35-0.40)\n")

    # 2. per-team: does a team get a CONSISTENT level, or random noise?
    per_team = df.groupby('team')['xGC'].agg(['mean', 'std', 'min', 'max'])
    per_team = per_team.sort_values('mean')
    print("PER-TEAM (sorted by mean xGC):")
    print(per_team)
    print(f"\nspread of team means: {per_team['mean'].std():.3f}")
    print(f"avg within-team std:  {per_team['std'].mean():.3f}")

    df['xGC'].hist(bins=30)
    return df, per_team
